<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('example')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_example.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('example.so')) return;
    } else {
      if (!dl('example.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class example {
	static function My_variable_set($My_variable) {
		My_variable_set($My_variable);
	}

	static function My_variable_get() {
		return My_variable_get();
	}

	static function fact($arg1) {
		return fact($arg1);
	}

	static function my_mod($n,$m) {
		return my_mod($n,$m);
	}
}

/* PHP Proxy Classes */

?>
